### ISSUE TITLE
Ошибку выдает Allowed memory

### ISSUE THREAD

**Issue by ars09** [k0ldbl00d/rkndownloader#1]
После недельной выгрузки, начало выдавать ошибку 
  Произошла ошибка при выгрузке реестра: Allowed memory size of 134217728 bytes exhausted (tried to allocate 6646

CONTAINER ID   NAME              CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O   PIDS
201e591c7419   eloquent_jepsen   0.00%     128KiB / 6.152GiB   0.00%     69.2MB / 1.43MB   0B / 0B     2

**Comment by k0ldbl00d** [comment]
Спасибо за обратную связь. Судя по всему, реестр разбух настолько что стандартного лимита памяти для процесса стало не хватать. Увеличил в 4 раза.

**Comment by k0ldbl00d** [comment]
Fixed in 6bee302
